name: egoal
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - ipykernel
  - tqdm
  ## GraphBLAS python wrapper 
  - python-graphblas
  ## For GPU support
  - cudatoolkit
  - pytorch=*=*cuda*
  ## for data analysis and visualisation
  - scikit-learn
  - scanpy
  - networkx
  #- zoopt
