name: egoal
channels:
  - conda-forge
  - pytorch
  

dependencies:
  - python
  - pip
  - numpy
  - pandas
  
  - cudatoolkit
  - pytorch=*=*cuda*
  - cupy

  - tqdm
  - openpyxl
  - ipykernel
  - cobra
  - torch-geometric
  - rdflib
  - scikit-learn
  - scanpy
  - networkx
  #- zoopt
